language : node_js

node_js :
  - stable

install:
  - cd lambda
  - npm install

script:
  - npm run coverage

# Send coverage data to Coveralls
after_script: "cat lambda/coverage/lcov.info | lambda/node_modules/coveralls/bin/coveralls.js"