module.exports = {
    SKILL_NAME: 'SKILL_NAME',
    WELCOME_MESSAGE: 'WELCOME_MESSAGE',
    WELCOME_REPROMPT: 'WELCOME_REPROMPT',
    HELP_MESSAGE: 'HELP_MESSAGE',
    HELP_REPROMPT: 'HELP_REPROMPT',
    EXIT_MESSAGE: 'EXIT_MESSAGE',
    
};